"""add_product_image_url

Revision ID: 66bd17bc64f1
Revises: a4d45372d03b
Create Date: 2026-05-14 10:22:28.363417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '66bd17bc64f1'
down_revision: Union[str, None] = 'a4d45372d03b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'image_url')
    # ### end Alembic commands ###
