"""add_delivery_location

Revision ID: b601bc70938f
Revises: fba817fe6841
Create Date: 2026-05-14 10:38:28.294477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b601bc70938f'
down_revision: Union[str, None] = 'fba817fe6841'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_current_latitude', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('delivery_current_longitude', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('delivery_location_updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_location_updated_at')
    op.drop_column('orders', 'delivery_current_longitude')
    op.drop_column('orders', 'delivery_current_latitude')
    # ### end Alembic commands ###
