"""add_payment_fields

Revision ID: fba817fe6841
Revises: 0d803a7d541f
Create Date: 2026-05-14 10:32:58.994708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fba817fe6841'
down_revision: Union[str, None] = '0d803a7d541f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_status', sa.Enum('pending', 'approved', 'rejected', 'refunded', name='paymentstatus'), nullable=False))
    op.add_column('orders', sa.Column('payment_id', sa.String(length=120), nullable=True))
    op.add_column('orders', sa.Column('checkout_url', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_orders_payment_id'), 'orders', ['payment_id'], unique=False)
    op.create_index(op.f('ix_orders_payment_status'), 'orders', ['payment_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_payment_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_payment_id'), table_name='orders')
    op.drop_column('orders', 'checkout_url')
    op.drop_column('orders', 'payment_id')
    op.drop_column('orders', 'payment_status')
    # ### end Alembic commands ###
